services:
  docs:
    image: kesamokki_local_docs
    container_name: kesamokki_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kesamokki:/app/kesamokki:z
    ports:
      - '9000:9000'
    command: /start-docs
