# Generated by Django 5.1.8 on 2025-04-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(max_length=120, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=120, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('country_code', models.CharField(default='FI', max_length=2)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to auth user', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
