# Generated by Django 5.1.8 on 2025-05-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0005_remove_reservation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Invoice Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('billed_at', models.DateField(verbose_name='Billed At')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
