# Generated by Django 5.1.8 on 2025-04-27 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.CharField(default='testing', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='valtteb@uef.fi', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='Valtteri Bovellan', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='+358401234455', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. It should contain 8-15 digits and may start with a + sign.', regex='^\\+?[0-9]{8,15}$')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
