# Generated by Django 5.1.8 on 2025-05-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_email_and_more'),
        ('users', '0003_customer_email_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='users.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
