# Generated by Django 5.1.8 on 2025-05-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='address',
        ),
    ]
